### ISSUE TITLE
Allow registering module icons in JS

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2143]
See https://github.com/google/site-kit-wp/pull/2115#discussion_r501283031, the `registerModule` action in the `core/modules` store should allow registering a module icon.

As part of this issue, we should also define criteria that all module icons should adhere to.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The optional `icon` property in the `registerModule` action of `core/modules` should be changed to not be a string, but a React component type (e.g. `AdSenseIcon`).
    - There should be no default, i.e. we shouldn't assume that every module has an icon.
    - The `icon` should be passed through with the module's settings into the reducer
* All six Site Kit modules in JS should include passing their `icon` in the `registerModule` call.
* There should be a new `getModuleIcon( slug )` selector on the `core/modules` store which returns the registered icon component for the given module slug, `null` if there is no icon for the module, or `undefined` if the module has not been registered.
* The `ModuleIcon` component should be updated to source its inner icon component from the `getModuleIcon` selector only
* All module icons should be square or render as squares without distortion when given the same `width` and `height`
* `ModuleIcon` should be updated to accept a `size` prop instead of `width` and `height` which should be passed as both `width` and `height` to the inner icon component
     - All use of `ModuleIcon` should be updated accordingly

## Implementation Brief

* Change the `icon` argument documentation to be a `WPComponent` https://github.com/google/site-kit-wp/blob/07d95eddab386c3c5b9f8d1dad1f123d7cb33dae/assets/js/googlesitekit/modules/datastore/modules.js#L222. As the component can be stored in the data store, no code needs to be updated to support storing the component.
* Remove https://github.com/google/site-kit-wp/blob/07d95eddab386c3c5b9f8d1dad1f123d7cb33dae/assets/js/components/ModuleIcon.js#L44-L46
* Replace https://github.com/google/site-kit-wp/blob/07d95eddab386c3c5b9f8d1dad1f123d7cb33dae/assets/js/components/ModuleIcon.js#L48 with `const ModuleIconComponent = useSelect( ( select ) => select( CORE_MODULES ).getModuleIcon( slug ) );`
* Update https://github.com/google/site-kit-wp/blob/07d95eddab386c3c5b9f8d1dad1f123d7cb33dae/assets/js/components/ModuleIcon.js#L43 to use `size = 33` instead of `width = 33, height = 33`, then pass `size` to both `width` and `height` props of `ModuleIconComponent`. (Update PropTypes as well.)
* Update `ModuleIcon` to return `null` if `ModuleIconComponent` is false-y.
* Change all instances of `<ModuleIcon slug={ slug } width={ size } height={ size } />` to be `<ModuleIcon slug={ slug } size={ size } />`:
    * https://github.com/google/site-kit-wp/blob/07d95eddab386c3c5b9f8d1dad1f123d7cb33dae/assets/js/components/modules-list.js#L144
    * https://github.com/google/site-kit-wp/blob/07d95eddab386c3c5b9f8d1dad1f123d7cb33dae/assets/js/components/setup-module.js#L129
    * https://github.com/google/site-kit-wp/blob/07d95eddab386c3c5b9f8d1dad1f123d7cb33dae/assets/js/components/notifications/notification.js#L262
    * https://github.com/google/site-kit-wp/blob/07d95eddab386c3c5b9f8d1dad1f123d7cb33dae/assets/js/components/settings/settings-module.js#L278 (keep `className` for this component as well)
* Add the new `icon` argument to each `Modules.registerModule` call for the appropriate component:
    * https://github.com/google/site-kit-wp/blob/07d95eddab386c3c5b9f8d1dad1f123d7cb33dae/assets/js/modules/adsense/index.js#L86 (`assets/svg/adsense.svg`)
    * https://github.com/google/site-kit-wp/blob/07d95eddab386c3c5b9f8d1dad1f123d7cb33dae/assets/js/modules/analytics/index.js#L46 (Analytics)
    * etc. for all `registerModule()` calls.

### Test Coverage

* Test coverage for the `ModuleIcon`, particularly around it outputting `null` when the `icon` prop isn't available would be good, but that's all that's required here I think.

### Visual Regression Changes

* Should not result in VRT changes.

## QA Brief

The module Icons must appear everywhere it already does. Some of the places to look for as follows:
* Open any module, the SVG module icon (usually positioned in top left) must appear everywhere it did before.
* Go to `/wp-admin/admin.php?page=googlesitekit-dashboard&notification=authentication_success`, all the module icons must appear in the congrats notification.
* Go to settings, the icons should appear in `connected services` and `connect more services` as they did before.
* All the stories which had module icons must look same. Some of them are:
	* Modules List
	* Page Headers
	* Traffic Increase win
	* `<Module>/Setup` stories
* If anything looks off (unusually positioned elements), check if an icon was there before these changes and if the icon disappeared then QA fails

## Changelog entry

* Allow registering module icon SVGs via the `core/modules` action `registerModule`.

**Comment by aaemnnosttv** [comment]
@felixarntz I've merged the ACs from the other issue here and updated the dependencies of the issue. Let me know if you think anything should change, otherwise I think it should be ready for IB 👍

**Comment by felixarntz** [comment]
IB ✅ 

@tofumatt 
> * Change all instances of `<ModuleIcon slug={ slug } width={ size } height={ size } />` to be `<ModuleIcon slug={ slug } size={ size } />`:

Note that in some cases the `width` and `height` are currently not the same, which I believe was originally done for more "perfect" alignment of the icon. Let's see what the outcome looks like - if needed, we may need to modify the icon SVGs or slightly alter the approach.

Overall we should try to keep things simple, and icons should be possible to use in square format. Otherwise we'd need to give modules including 3P control about that too, which would become way too much micromanagement IMO.

**Comment by felixarntz** [comment]
@kostyalmm Can you still add a QA Brief to this one? Might be good to require testing that icons for the different modules still show up throughout applicable UI (e.g. module screens, module setup flows, module settings panels) and that the Storybook stories for module settings and module setup still show up correctly.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

To test this I compared a site on latest release and one on develop branch + checked alongside the stories. 

- When opening all modules, the SVG module icon appears in the top left - [Screenshot](https://user-images.githubusercontent.com/73545194/101777555-97b94280-3b2d-11eb-8144-05a360f6bd31.png)

- The authentication success page lists all the module icons in the congrats notification - [Screenshot](https://user-images.githubusercontent.com/73545194/101777320-4610b800-3b2d-11eb-8781-467a3dad3797.png)

- The icons appeared in the `connected services` and `connect more` tabs as before - [Screenshot](https://user-images.githubusercontent.com/73545194/101777201-1792dd00-3b2d-11eb-9192-5de79477bb30.png)   - [Screenshot 1](https://user-images.githubusercontent.com/73545194/101777280-33967e80-3b2d-11eb-8489-6d37174cb52a.png)
- Disconnected site and reset data and set up SK and reconnected services to compare icons between latest release and develop branch.  Compared this also with the stories.

**Comment by wpdarren** [comment]
_Note. I've put this back to QA because I'd like to run these tests on mobile devices._
