### ISSUE TITLE
Hovering over All Traffic pie slice tooltip should not cause flickering

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2709]
When hovering over a pie slice in the `UserDimensionsPieChart` in the new All Traffic widget, its tooltip shows up. However, if the tooltip also covers the area where you're hovering, it causes a flickering effect - since you're technically no longer hovering the pie slice in that case.

This should be fixed: When hovering the pie slice, the tooltip should appear even when then the cursor is above that tooltip.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When hovering over a pie slice in the All Traffic widget and then the cursor is on the tooltip that comes up, the tooltip should remain opened until hovered away, instead of flickering.

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment]
IB = CR = ✅

**Comment by felixarntz** [comment]
**QA** ⚠️ 

It isn't possible now to access links in the tooltips anymore. Not sure whether it's caused by this issue or #2701. @aaemnnosttv @eugene-manuilov Can we maybe achieve it so that the tooltip remains there as long as you hover over the pie slice _or_ the tooltip?

cc @marrrmarrr

**Comment by eugene-manuilov** [comment]
@felixarntz it should be fixed now. Could you please take a look at #2718?

**Comment by wpdarren** [comment]
### QA Update: Failed ❌ 

@eugene-manuilov @felixarntz 

I am still seeing flickering in a specific scenario:  

Hover over a slice in the pie chart, but do not click it.  You will see a tooltip appear, hover over it, and it starts flickering.  

When you select the slice and hover over the tooltip, then the tooltip does not flicker. 

![tooltips](https://user-images.githubusercontent.com/73545194/106215000-f84e2d00-620a-11eb-9507-57d12658198d.gif)

**Comment by felixarntz** [comment]
@wpdarren Did you test using the `master` branch? Since we've already branched off to `master` for the upcoming 1.25.0 release, all issues that are still being worked on and that are tagged for 1.25.0 need to be QAd on the `master` branch.

Double-checking since it works for me on `master`.

**Comment by wpdarren** [comment]
@felixarntz  I am seeing the other changes implemented to this feature.  I tested with 1.24.0 activated and used the tester plugin to connect to the develop branch and development build. I also checked on 1.25.0 with develop branch and development build and could recreate the issue reported.  When you click on the slice it is fine, but when you just hover over the tooltip it flickers. I don't have a local site with any data.

**Comment by felixarntz** [comment]
@wpdarren Yes, with the `develop` branch this is still an "expected" bug right now. Since it is part of the 1.25.0 release, the fix is right now only present in the `master` branch. Can you retest using a build from the `master` branch? E.g. the latest production build from https://github.com/google/site-kit-wp/wiki/refs/heads/master/google-site-kit.zip

**Comment by wpdarren** [comment]
@felixarntz Ahh, sorry, misunderstood. Yes, I will do that now.

**Comment by wpdarren** [comment]
### QA Update: Pass ✅ 

The tooltip no longer flickers when you hover over the tooltip of a slice.

![image](https://user-images.githubusercontent.com/73545194/106219412-40258200-6214-11eb-81f3-0483ed3db640.png)
