### ISSUE TITLE
Unknown Error after Signing IN

### ISSUE THREAD

**Issue by phpbits** [google/site-kit-wp#4]
Happening on Step 2, after allowing the API and signed in, it's throwing this on the dashboard:

<img width="1116" alt="Screen Shot 2019-06-20 at 12 11 18 PM" src="https://user-images.githubusercontent.com/3365507/59818004-b4b7ef80-9354-11e9-8313-a8e245b3861f.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* 

## Acceptance criteria

*

**Comment by jamesozzie** [comment]
@phpbits Just to confirm, after step 2 was complete it never directed you to step 3? (to verify the URL).

If possible can you clear your cache and then reset your Sit Kit (Settings > Admin Settings > Reset Site Kit). Also ensure you don't have any API restrictions also and authenticate via the same Google account with which you created OAuth credentials with.

**Comment by phpbits** [comment]
@jamesozzie it's on step 2. I'll try that. Thanks!

**Comment by phpbits** [comment]
@jamesozzie No Settings nav available. I can't get pass here :

<img width="1097" alt="Screen Shot 2019-06-20 at 7 25 39 PM" src="https://user-images.githubusercontent.com/3365507/59846003-578e5f00-9391-11e9-88c8-528dc2c4bb8e.png">

After clicking the "Allow" buttons, I've been redirected to my original screenshot with "Unknown Error" printed.

**Comment by jamesozzie** [comment]
In order for me to investigate or log as a bug can you inform me of the below:

WordPress version: 
PHP Version: 
Operating System: 
WordPress plugin being uses:

Do you have any other WordPress installs on the same server you can try with?

**Comment by gioangion** [comment]
Same here. Can't get past step #2.

WordPress version: 5.2.2–it_IT
PHP Version: 5.6.35
Operating System: Linux

**Comment by bigmike7801** [comment]
Getting the same issue here after step 2.

Here's some errors in my logs:

`#0 /domXXXXX/wp-content/plugins/google-site-kit/vendor/google/apiclient/src/Google/Client.php(340): Google\Auth\OAuth2->buildFullAuthorizationUri(Array)
#1 /domXXXXX/wp-content/plugins/google-site-kit/includes/Core/Authentication/Clients/OAuth_Client.php(455): Google_Client->createAuthUrl()
#2 /domXXXXX/wp-content/plugins/google-site-kit/includes/Core/Authentication/Authentication.php(443): Google\Site_Kit\Core\Authentication\Clients\OAuth_Client->authorize_user()
#3 /domXXXXX/wp-content/plugins/google-site-kit/includes/Core/Authentication/Authentication.php(189): Google\Site_Kit\Core\Authentication\Authentication->handle_oauth()
#4 /wordpress-4.9.10/wp-includes/class-wp-hook.php(286): Google\Site_Kit\Core\Authentication\Authentication->Google\Site_Kit\Core\Authentication\{closure}('')
#5 /wordpress-4.9.10/wp-includes/class-wp-hook.php(310): WP in /dom16750/wp-content/plugins/google-site-kit/vendor/google/auth/src/OAuth2.php on line 651`

WP Version 4.9.10
PHP 7.1.29-1+ubuntu16.04.1+deb.sury.org+1
Zend Engine v3.1.0 with Zend OPcache v7.1.29

**Comment by phpbits** [comment]
WordPress version:  5.2.2
PHP Version: 7.3.4
Operating System: Linux
Plugins:
Akismet Anti-Spam | Version 4.1.2 by Automattic
Autoptimize | Version 2.5.1 by Frank Goossens (futtta)
Block Gallery | Version 1.1.6 by Rich Tabor
CoBlocks | Version 1.10.0 by GoDaddy
Easy Login Styler | Version 1.0.6 by Phpbits Creative Studio
[EditorsKit](https://wordpress.org/plugins/block-options/) | Version 1.7 by Jeffrey Carandang
Gutenberg | Version 5.9.2 by Gutenberg Team
SEOPress | Version 3.5.8 by Benjamin Denis
SEOPress PRO | Version 3.5.8 by Benjamin Denis

**Comment by 1wayrocker** [comment]
I received the **Unknown Error** myself. I noticed that my OAUTH Credentials was using a non-ssl and my website was using a ssl. Adjusted the Site Address (URL) and WordPress Address (URL) in WP Settings and re-authorized. Step 2 completed. Hope that can help

**Comment by jamesozzie** [comment]
Great catch @1wayrocker I was able to replicate the same error. @phpbits Can you check your "WordPress Address (URL)” and “Site Address (URL)" from the general settings in your WordPress setup?

**Comment by bigmike7801** [comment]
> I received the **Unknown Error** myself. I noticed that my OAUTH Credentials was using a non-ssl and my website was using a ssl. Adjusted the Site Address (URL) and WordPress Address (URL) in WP Settings and re-authorized. Step 2 completed. Hope that can help

This fixed it for me too.

**Comment by phpbits** [comment]
> Can you check your "WordPress Address (URL)” and “Site Address (URL)" from the general settings in your WordPress setup?

Fixes the issue! My addresses isn't https on these fields. Changed and works perfectly now ;) Thanks!

**Comment by jamesozzie** [comment]
Great news @phpbits, and thanks for pointing this out @bigmike7801.

**Comment by easytraxbd** [comment]
![image](https://user-images.githubusercontent.com/46297281/60321478-b5790300-999e-11e9-91fe-9579d9afd86a.png)

I fixed it by making WP site URL settings and actual live URL. One was https and another was http. Both has to be same.

**Comment by felixarntz** [comment]
@marrrmarrr @ThierryA We need to investigate a bit more what we can do about this.

**Comment by yosef-coachella** [comment]
I am still getting this same error.
In my General settings everything is HTTPS:
<img width="662" alt="Image 2019-07-10 at 20 02 59" src="https://user-images.githubusercontent.com/52765180/61012812-f7fef000-a34d-11e9-8d6f-19f6f26cd2d7.png">
But Google keeps putting HTTP:
<img width="804" alt="Image 2019-07-10 at 19 59 53" src="https://user-images.githubusercontent.com/52765180/61012837-19f87280-a34e-11e9-8060-0c85228427bb.png">
<img width="1142" alt="Image 2019-07-10 at 19 58 19" src="https://user-images.githubusercontent.com/52765180/61012849-2b417f00-a34e-11e9-8d28-38b4a805603e.png">

I'm not sure what I can do from here...

**Comment by yosef-coachella** [comment]
Well, I went into Google APIs account and manually edited the oauth credentials to add the URL with HTTPS. I downloaded the new JSON, copied the text, pasted back into the Site Kit dashboard. now it works.

**Comment by jamesozzie** [comment]
@felixarntz I'll keep this open if you want to re-assign or work on a fix, in particular where sites uses https but don't redirect non https.

**Comment by rameshgrg** [comment]
hello there 
i cant get pass the email authentication
both my wordpress and site url has HTTPS
I tried several time after clearing cache and deactivating few other plugins --- but no luck
if any of you hav fixed this issue with site kit please do let us know 
thanks

**Comment by jamesozzie** [comment]
@rameshgrg Do you mind trying from an incognito window using Chrome? Also please test with another theme active (You can revert back to your current theme after). If that doesn't work please check your console for any [errors](https://i.imgur.com/f5WfLb3.png) and paste them here.

**Comment by yosef-coachella** [comment]
I don't know if this is a connected issue but Console, Analytics, and Speed are all connected but data is never loaded. Just hours and hours of the dashboard looking like it is about to load something...


![Screen Recording 2019-07-11 at 14 40](https://user-images.githubusercontent.com/52765180/61076289-e10ddb80-a3e9-11e9-9eae-2d9d1aa6ab4d.gif)
![Screen Recording 2019-07-11 at 14 37](https://user-images.githubusercontent.com/52765180/61076126-82e0f880-a3e9-11e9-9dff-2ef8b85b644e.gif)

Any suggestions?

**Comment by jamesozzie** [comment]
@yosef-coachella Do you have iThemes security installed? If so can you disable the _"Limits the number of characters that can be sent in the URL"_ option? If you are not using this plugin can you confirm what other plugins you are using, and also please try with plugins deactivated and incognito mode.

**Comment by zaheer039** [comment]
I can solve you unknown error issue in google site kit just custom order me on [fiverr](https://www.fiverr.com/zaheer639)

**Comment by solamathew** [comment]
> I received the **Unknown Error** myself. I noticed that my OAUTH Credentials was using a non-ssl and my website was using a ssl. Adjusted the Site Address (URL) and WordPress Address (URL) in WP Settings and re-authorized. Step 2 completed. Hope that can help

This worked for me too. 

After setting the URL to HTTPS, I cleared cache before proceeding and it worked.

Thanks.

**Comment by solamathew** [comment]
> I don't know if this is a connected issue but Console, Analytics, and Speed are all connected but data is never loaded. Just hours and hours of the dashboard looking like it is about to load something...
> 
> ![Screen Recording 2019-07-11 at 14 40](https://user-images.githubusercontent.com/52765180/61076289-e10ddb80-a3e9-11e9-9eae-2d9d1aa6ab4d.gif)
> ![Screen Recording 2019-07-11 at 14 37](https://user-images.githubusercontent.com/52765180/61076126-82e0f880-a3e9-11e9-9dff-2ef8b85b644e.gif)
> 
> Any suggestions?

Same with me...

Need Help

**Comment by jamesozzie** [comment]
@solamathew What plugins do you have installed, specifically caching or security plugins? If using iThemes there is an option you can toggle in the [settings](https://i.imgur.com/7OyyYyI.png) relating to URL string limits.

**Comment by yosef-coachella** [comment]
For me the problem was caused by a security plugin called Webarx. When I contacted tech support  they replied: "It probably collides with our plugin since we use a chart on the dashboard as well."
As such they were unable to offer a fix but implied that in a future update they may fix their code to prevent tis.

**Comment by jamesozzie** [comment]
Closing this as resolved. Inputting the "https" and matching the Site Address (URL) and WordPress Address (URL) resolved submitters issue. 

@solamathew The issue you are experiencing is more related to #150

**Comment by stylestrends** [comment]
Just Change URL into **WP Admin >> Setting > General > Website Url > if Http:// Then add https://**

**Comment by stylestrends** [comment]
> > I don't know if this is a connected issue but Console, Analytics, and Speed are all connected but data is never loaded. Just hours and hours of the dashboard looking like it is about to load something...
> > ![Screen Recording 2019-07-11 at 14 40](https://user-images.githubusercontent.com/52765180/61076289-e10ddb80-a3e9-11e9-9eae-2d9d1aa6ab4d.gif)
> > ![Screen Recording 2019-07-11 at 14 37](https://user-images.githubusercontent.com/52765180/61076126-82e0f880-a3e9-11e9-9dff-2ef8b85b644e.gif)
> > Any suggestions?
> 
> Same with me...
> 
> Need Help

Same here bro...

**Comment by jamesozzie** [comment]
@stylestrends Others have reported the same issue, not specifically in this issue. In many cases there is a configuration setting in a security or caching which can solve this issue. Please inform me what caching or security plugins you are using.

**Comment by hadifarnoud** [comment]
many users like me get this issue because their server cannot connect to Google. withgoogle.com blocked Iran IPs and all sites from thoses IPs have no luck.

I do not know how to fix this tbh
