### ISSUE TITLE
Create GA4 `SearchFunnelWidget`

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6217]
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new component `SearchFunnelWidgetGA4` should be created based on the existing `SearchFunnelWidget`
* The component should source its report data from the `analytics-4` store
	* [See here for a table of equivalent metrics for GA4](https://docs.google.com/document/d/17RKIrdm5PBK8j6rP0GV_2QlztSLXqYQX8ikz3kQmrAo/edit?resourcekey=0-njOU7bn1dhvi5Yp2jeX5zw#bookmark=id.2cvsdbn818e6)
* No changes should be made in the dashboard yet
* Storybook stories should be added to cover the following cases (with and without a current entity URL set: [example](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-widgets-dashboardoverallpagemetricswidget--ready)):
    * Loading
    * Gathering data ("Data unavailable")
    * Zero data (data available but metric is `0`) 
    * Error
    * Ready (data available and non-zero)

## Implementation Brief
* Once #6173 and #6174 have been merged.
* Copy `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/index.js` to `assets/js/modules/search-console/components/dashboard/SearchFunnelWidgetGA4/index.js` with the following changes:
    * The exported component should be updated to `SearchFunnelWidgetGA4`.
    * Replace occurrences of the Analytics data store (`MODULES_ANALYTICS`) by the GA4 Analytics data store (`MODULES_ANALYTICS_4`) excerpt for the `getGoals` selector call (see further below).
    * Replace the metrics and dimensions by their GA4 counterparts [as per the doc here](https://docs.google.com/document/d/17RKIrdm5PBK8j6rP0GV_2QlztSLXqYQX8ikz3kQmrAo/edit?resourcekey=0-njOU7bn1dhvi5Yp2jeX5zw#bookmark=id.2cvsdbn818e6), including the metric names.
    * No need to duplicate child components which do not make use of the Analytics module but instead include them directly from `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/`.
* Goals don’t exist anymore in GA4 and are replaced by conversion events.
    * Copy `assets/js/modules/analytics/datastore/goals.js` to `assets/js/modules/analytics-4/datastore/conversion-events.js` with the following changes:
        * The initial state should consist of the `conversionEvents` with `undefined` as default value.
        * The `getGoals` selector should be named `getConversionEvents`. Other parts in the code should be updated to reflect that change, i.e renaming goals to conversion events.
        * An API request should be made to the `conversion-events` REST endpoint for the Analytics 4 module (see #6348 ).
* Using `assets/js/modules/search-console/components/dashboard/SearchFunnelWidgetGA4/index.js`, replace usage of the `getGoals` selector by `getConversionEvents`.
* Stories should be within `assets/js/modules/search-console/components/dashboard/SearchFunnelWidgetGA4/index.stories.js` and make use of the Analytics 4 response mock data added from #6174
        * Refer to the AC for the different stories to be added.

### Test Coverage
* Add tests for the the `conversion-events` data store partial similar to `assets/js/modules/analytics/datastore/goals.test.js`

## QA Brief

* This is currently only testable in Storybook.
* Check the stories under **SearchConsole > Widgets > SearchFunnelWidgetGA4**. These should be broadly in line with the existing UA version under **SearchConsole > Widgets > SearchFunnelWidget**, except with the following changes:
	* `Goals` -> `Conversions`
	* `Bounce Rate` -> `Engaged Sessions`
* [PR Storybook](https://google.github.io/site-kit-wp/storybook/pull/6596/?path=/story/modules-searchconsole-widgets-searchfunnelwidgetga4--ready) (will be deleted when merged to `develop`).
* [`develop` Storybook](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-searchconsole-widgets-searchfunnelwidgetga4--ready).
* [`main` Storybook](https://google.github.io/site-kit-wp/storybook/main/?path=/story/modules-searchconsole-widgets-searchfunnelwidgetga4--ready).
* The associated PR fixes the #6587 bug for GA4 version. Ensure that it is fixed in the gathering data state stories.

### Screenshots

![Screenshot 2023-03-03 at 8 38 49 PM](https://user-images.githubusercontent.com/24408261/222755600-68ec3fba-9594-49ae-8bfb-f32f15d3f29f.png)
![Screenshot 2023-03-03 at 8 38 58 PM](https://user-images.githubusercontent.com/24408261/222755620-d5e07f5c-3f22-49fb-9025-e03d12eafcb9.png)
![Screenshot 2023-02-17 at 8 59 30 PM](https://user-images.githubusercontent.com/24408261/219696457-2ebeb958-19c4-49d8-a96f-6805105ff886.png)
![Screenshot 2023-02-17 at 8 59 38 PM](https://user-images.githubusercontent.com/24408261/219696509-3efcb432-ea6e-47b5-b4c4-102667c58a09.png)
![Screenshot 2023-02-16 at 6 57 50 PM](https://user-images.githubusercontent.com/24408261/219380380-909d40d7-6e83-4b82-84a8-202888ba3159.png)
![Screenshot 2023-02-16 at 6 58 01 PM](https://user-images.githubusercontent.com/24408261/219380377-09d1495f-0aef-4fca-8526-b2a1e9a8f8fb.png)
![Screenshot 2023-02-16 at 6 58 10 PM](https://user-images.githubusercontent.com/24408261/219380373-85d95121-4014-40d9-9d6e-254482095f5e.png)
![Screenshot 2023-03-03 at 8 41 32 PM](https://user-images.githubusercontent.com/24408261/222756169-81d6f562-a48a-4046-9f08-5d319cff3d14.png)
![Screenshot 2023-02-16 at 6 58 30 PM](https://user-images.githubusercontent.com/24408261/219380365-66d134ae-99aa-4344-b4f3-ff22a10465f5.png)
![Screenshot 2023-02-16 at 6 58 38 PM](https://user-images.githubusercontent.com/24408261/219380363-a1ff7d26-0ecb-4899-b526-96d0763ca7a5.png)
![Screenshot 2023-02-16 at 6 58 46 PM](https://user-images.githubusercontent.com/24408261/219380362-d8c8e66a-0974-4714-a8a7-74f3593a1895.png)
![Screenshot 2023-03-03 at 8 39 18 PM](https://user-images.githubusercontent.com/24408261/222755657-6726004b-46e3-4a5f-b6f0-a1e7cd6309a2.png)

## Changelog entry

* Add a copy of the Search Funnel widget that works with Google Analytics 4 data.

**Comment by asvinb** [comment]
@aaemnnosttv Can you take a look at the IB, especially for the "goals" part. Not sure if we have should have the `conversion-events` endpoint created in the current ticket or it' a separate ticket.

**Comment by aaemnnosttv** [comment]
@asvinb good call, I didn't realize this would require a separate endpoint but that makes sense as Goals today also requires one. Would you please open a separate issue for adding that? Feel free to add initial AC and IB there and then send it my way. Then we can remove that part of the IB here and make this issue dependent on that one. Thanks for asking!

**Comment by asvinb** [comment]
@aaemnnosttv #6348 created for the `conversion-events` endpoint and assigned to you.

**Comment by tofumatt** [comment]
IB ✅

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@hussain-t have a few differences which need highlighting. 

1. I have noticed that the `Unique Visitors from Search` on `Ready` has a different format for the y-axis in the chart.  The formatting in non GA4 is 25, 50, 75, 100 and 125 where as the for GA4 it is 2.5, 5.0, 7.5, 10.0 and 12.5 and this means that the graph is different too.  See screenshot below. 

![image](https://user-images.githubusercontent.com/73545194/222294407-4f8d6f55-0a20-4607-9b93-8970bf405e9d.png)

2. I have noticed that the `Goals - Conversions`' on '`Ready` has a different format for the y-axis in the chart. The formatting in non GA4 is 25, 50, 75, 100 and 125 where as the for GA4 it is 0, 2, 4, 6, 8, 10 and this means that the graph is different too. See Screenshot below. 

![image](https://user-images.githubusercontent.com/73545194/222295235-a45b4430-191d-4363-97dc-5924827bde41.png)

 3. I noticed on all stories other than `Ready` for non GA4, there's no Goals data, whereas on the GA4 version, the conversions field does appear. This might be an issue with the storybook and not linked to this change but thought it was worth highlighting. 

![image](https://user-images.githubusercontent.com/73545194/222296010-dcb8c2e1-3122-4891-8fdf-fb71282f5019.png)

4. I noticed on all stories other than `Ready` for both GA4 and non, that `Error in Google Chart` message was appearing. Is this expected?  I was expecting to see charts on all of those stories for the data that was appearing. For example in the screenshot below, we have `Total impressions` and `Total clicks` data for search console but no chart appears. 

![image](https://user-images.githubusercontent.com/73545194/222296789-89c672a8-03df-47cc-9b1c-0f6b16637c32.png)

5. When looking at the `Ready Entity Dashboard` the non GA4 `Bounce rate format` is 14.26% whereas on GA4 for `Engaged sessions` the format is 14% so the two are displaying different data in this scenario. 

![image](https://user-images.githubusercontent.com/73545194/222298803-423135fc-7aaf-4e1e-8ac5-e59a380fd9de.png)

**Comment by hussain-t** [comment]
Thanks, @wpdarren. I will investigate the `#1`, `#2`, and `#5` observations. I noticed that the dates disappeared in the x-axis for the GA4 version.

> 3. I noticed on all stories other than Ready for non GA4, there's no Goals data, whereas on the GA4 version, the conversions field does appear. This might be an issue with the storybook and not linked to this change but thought it was worth highlighting.

The `Goals` section is missing in the UA versions. However, I thought it would be better to display the `Conversions` and that's the reason I have added it.

> 4. I noticed on all stories other than Ready for both GA4 and non, that Error in Google Chart message was appearing. Is this expected? I was expecting to see charts on all of those stories for the data that was appearing. For example in the screenshot below, we have Total impressions and Total clicks data for search console but no chart appears.

That's an existing issue with the chart. It's not related to this ticket. If you refresh the page, it should work. However, if you click other stories and come back, it will show the error. So you will have to refresh the page again.

**Comment by hussain-t** [comment]
@wpdarren, I have addressed the issues `#1`, `#2`, and `#5` in this follow-up [PR](https://github.com/google/site-kit-wp/pull/6675).

>5. When looking at the Ready Entity Dashboard the non GA4 Bounce rate format is 14.26% whereas on GA4 for Engaged sessions the format is 14% so the two are displaying different data in this scenario.

FYI, this is not a data issue but a format issue. Engaged Sessions should be a regular integer and not a percentage. This has been fixed.

![Screenshot 2023-03-02 at 10 42 18 PM](https://user-images.githubusercontent.com/24408261/222502084-9be25ac6-afdf-45b7-816c-1fb41e52e844.png)

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@hussain-t I have cleared cache and refreshed Storybook a few times but I am still seeing issue 1 and 2 on the charts on the y-axis.  

Also, while the formatting issue for issue 5 with removing the percentage is fixed, I noticed that we still have reference the percentage in the chart. I am assuming that this needs to be removed too? 

![image](https://user-images.githubusercontent.com/73545194/222610198-278ea904-3984-4988-8696-f148d3fa4e2d.png)

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@hussain-t as per our conversation in Slack. 

I have sent this ticket back due to the percent mention in the chart for engaged sessions as per the screenshot above.

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@hussain-t I am sorry, I didn't mark it on my earlier screenshot but I also meant the percentage in the tooltip on the chart too. Basically, since this is an integer, we need to remove any reference to a percentage format. 

![image](https://user-images.githubusercontent.com/73545194/223141283-f99b5e03-5639-484f-9cb5-12239512fb4a.png)

**Comment by wpdarren** [comment]
### QA Update: ✅ 

**Verified:**

- Checked the stories under `SearchConsole > Widgets > SearchFunnelWidgetGA4` that they are in line with the existing UA version under `SearchConsole > Widgets > SearchFunnelWidget`, except with the following changes:
  - Goals -> Conversions
  - Bounce Rate -> Engaged Sessions
- The associated PR fixes the 6587 bug for GA4 version. The gathering data state stories are fixed.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/223432021-e9a43e51-0292-40aa-8564-5e821120d518.png)
![image](https://user-images.githubusercontent.com/73545194/223432048-c1693c72-e832-4d6b-85db-c8e0320f0cc8.png)
![image](https://user-images.githubusercontent.com/73545194/223432076-0aef94c6-4ff7-40ad-9f7e-f8ec767a2143.png)
![image](https://user-images.githubusercontent.com/73545194/223432101-86d96a10-58fa-472f-a100-22b2203124a9.png)
![image](https://user-images.githubusercontent.com/73545194/223432129-52df2a48-6b40-45a8-8498-b0029a54be7a.png)
![image](https://user-images.githubusercontent.com/73545194/223432165-f72f2f2c-7bcc-409f-8cd6-0d12db5cdf6f.png)

</details>

**Note:** The the ‘Engaged Sessions’ data is currently an integer but should be a percentage. We've decided to create a new ticket to fix this due to the confusion around this data.  

![image](https://user-images.githubusercontent.com/73545194/223432305-e5724b3f-9db6-445e-a939-ebab20372e0f.png)

**Comment by techanvil** [comment]
Note that I created https://github.com/google/site-kit-wp/issues/6724 to update the Engagement Rate (previously Engaged Sessions) metric to be a percentage.
