### ISSUE TITLE
Inconsistent behavior for Apply Changes button in selection panel

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7467]
## Bug Description

Update: This is not a bug but behaviour that is consistent with some other Module Settings forms where the Save action button is disabled if nothing on the form has actually changed, ie. the same settings are being selected or reselected as the settings that were present when opening the settings panel.

Original Description:
As reported by @bethanylang in Bug Bash:

The behavior for the selection panel's Apply Changes button can be inconsistent; even if I have more than two metrics selected, sometimes it does not allow me to apply changes. See video: https://app.screencast.com/jyYWzJUXqQDKs

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When the Key Metrics selection panel is opened for the first time, the save button text should continue to be "Save selection".
* When the selection panel is opened again with a set of selected metrics, the save button text should also be "Save selection". As soon as the user makes any changes to their selection, the save button text should change to "Apply changes". If the user ends up reselecting the exact same metrics that were selected when the panel was first opened (i.e. the metrics haven't changed), the button text should again be changed to "Save selection".
* This save button should not be disabled if the user has not updated the key metrics selection or if the user updated the selection but eventually selected the same key metrics that the panel opened with.

## Implementation Brief

Within `assets/js/components/KeyMetrics/MetricsSelectionPanel/Footer.js`:

- Update the rendered `SpinnerButton` as follows.
  - Remove the check for `haveSettingsChanged` from the `disabled` condition.
  - Update the condition that determines the label (i.e. its `children`):
    - If there are saved metrics _and_ the settings have changed - i.e., `savedMetrics?.length > 0 && haveSettingsChanged`, then the label should be _Apply changes_.
    - Otherwise, it should be _Save selection_.

### Test Coverage

- Update any failing JS/VRT tests.

## QA Brief

* Setup analytics
* Enable `ga4reporting` and `userInput` feature flags
* Setup suggested key metrics and after saving go back to dashboard
* Click on Change metrics link
* Verify that save button label is `Save selection`
* Change selection, by unchecking selected values and changing to different options
* Verify that button label is `Apply changes`
* Select back the options that were originally saved
* Verify that button label is `Save selection` again
* Verify that button stays disabled while panel is closing, there shouldn't be any flickering

## Changelog entry

* Improve copy in "Change metrics" sidebar panel.

**Comment by techanvil** [comment]
AC :white_check_mark:

**Comment by techanvil** [comment]
Np, thanks for the heads up @jimmymadon! This is updated and back in IBR :+1:

**Comment by tofumatt** [comment]
IB ✅

**Comment by tofumatt** [comment]
(Waiting to move to QA because we need a new release to tag this one with.)

**Comment by wpdarren** [comment]
### QA Update: ⚠️ 

@zutigrm @jimmymadon this passes the QAB and AC, but I do have an observation that I'd like to share.  

When you select on the `Apply selection` or `Save selection` button, it becomes disabled and the loading animation appears as expected, but just before the metrics panel closes, the button changes to active state, and appears as `Save selection` for a fraction of a second.   I have attached a screencast, with slow 3G set to see the behaviour better. 

Interested in your thoughts. 

https://github.com/google/site-kit-wp/assets/73545194/74f86c10-e938-4030-bfaf-8286dfb9ea83


**Verified:**

- When the Key Metrics selection panel is opened for the first time, the save button text should be `Save selection`.
- When the selection panel is opened again with a set of selected metrics, the save button text is still set to "Save selection". - As soon as the user makes any changes to their selection, the save button text changes to "Apply changes". 
- When the user ends up reselecting the exact same metrics that were selected when the panel was first opened, the button text is again be changed to "Save selection".
- The save button is not disabled if the user has not updated the key metrics selection or if the user updated the selection but eventually selected the same key metrics that the panel opened with.

![image](https://github.com/google/site-kit-wp/assets/73545194/b7704b5a-7e73-4aa8-a9a6-aadc4e0f0ac8)
![image](https://github.com/google/site-kit-wp/assets/73545194/8e3eff41-17ce-4ae3-9225-90b9a7b08ac5)
![image](https://github.com/google/site-kit-wp/assets/73545194/7a73ed09-1e84-4464-863c-0a1e8f0dc1d7)
![image](https://github.com/google/site-kit-wp/assets/73545194/34a2a29f-3f70-425c-b69f-37e4760000f9)

**Comment by kuasha420** [comment]
@wpdarren Back to you for another pass, the flicking issue should be solved now.

**Comment by wpdarren** [comment]
QA Update: ⚠️ 

@zutigrm @kuasha420 I am still seeing the flicker after clicking on the save/apply changes button.  It's only for a second that you see it, and more prominent on Slow 3G.  I see the PR is merged to develop, which I am on. Used a new site but cleared local/session storage and also cookies and still occurs.  Would you be able to take a look on an InstaWP site to see if you can recreate this and that's not an issue on my end? 

I realise this is super minor, but, it's an odd UX.

**Comment by mohitwp** [comment]
@wpdarren
Tested on slow 3g network.
When metrics panel closes, the button changes it's state to active state, but it's not changing the title for me.

https://github.com/google/site-kit-wp/assets/94359491/2141873d-fcef-4c20-895b-6d1a9cfaec45

**Comment by wpdarren** [comment]
### QA Update: ❌ 

@kuasha420 @zutigrm the flicker still occurs for me and does for Mohit as you can see from his screenshot above. 

This is really minor, but is an odd UX.

**Comment by zutigrm** [comment]
@wpdarren Just to confirm, by still seeing flicker, are you referring to original comment of button label changing, or button disable/enable state change during closing? 
I was working on button label changing during panel closing - which was defined as flickering issue on previous ticket. That one I cannot reproduce (on mohit's video label is not changing either). @kuasha420 Are you able to reproduce label change?

**Comment by wpdarren** [comment]
@zutigrm sorry for the confusion. No it wasn'r an issue with the label changing, but the button changed from inactive to active while the panel is closing.  I've just tested this again with a fresh pair of eyes and everything seems to be fine now. 👍 Maybe it was a caching issue that I was having. 

### QA Update: ✅ 

**Verified:**

- When the Key Metrics selection panel is opened for the first time, the save button text should be `Save selection`.
- When the selection panel is opened again with a set of selected metrics, the save button text is still set to  `Save selection`. - As soon as the user makes any changes to their selection, the save button text changes to `Apply changes`. 
- When the user ends up reselecting the exact same metrics that were selected when the panel was first opened, the button text is again be changed to  `Save selection`.
- The save button is not disabled if the user has not updated the key metrics selection or if the user updated the selection but eventually selected the same key metrics that the panel opened with.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/b7704b5a-7e73-4aa8-a9a6-aadc4e0f0ac8)
![image](https://github.com/google/site-kit-wp/assets/73545194/8e3eff41-17ce-4ae3-9225-90b9a7b08ac5)
![image](https://github.com/google/site-kit-wp/assets/73545194/7a73ed09-1e84-4464-863c-0a1e8f0dc1d7)
![image](https://github.com/google/site-kit-wp/assets/73545194/34a2a29f-3f70-425c-b69f-37e4760000f9)

</details>

**Comment by aaemnnosttv** [comment]
@tofumatt @techanvil it looks like we're still submitting the request to save the settings even when nothing is changed. Let's consider opening an issue to skip this if unnecessary.

**Comment by techanvil** [comment]
Hey @aaemnnosttv, that's an interesting point. To be honest, it makes me question the UX choice we've made here - if we are going to make it so clicking the button effectively does nothing when the settings aren't changed, maybe it should be disabled after all?

OTOH, if we do want to keep it enabled for a simpler UI, I think that pressing the button should still have a tangible action associated with it - i.e., pressing "Save" should still legitimately save the settings, even if none have changed in the local state. It's worth bearing in mind this _could_ still have some utility if the settings have been updated elsewhere, in which case a user could rightly expect that pressing save on an open tab would restore their state to that tab's view of the world...

**Comment by aaemnnosttv** [comment]
> It's worth bearing in mind this _could_ still have some utility if the settings have been updated elsewhere, in which case a user could rightly expect that pressing save on an open tab would restore their state to that tab's view of the world...

@techanvil wouldn't it override the settings if they had been updated elsewhere though? In this case, the user wouldn't see things updated on either side because they'd be persisting the current state. In either case, one of the tabs would change on refresh from state changing in different places. This is probably not a scenario we should be particularly worried about. My understanding was that the intention was to simplify the UI so that there was always a "happy-path" forward. I didn't expect it to still try to save in this scenario, but it's not exactly an "expensive" action to avoid even if it is unnecessary. I can go either way on it, but wanted to get your thoughts.

**Comment by techanvil** [comment]
@aaemnnosttv, yup, that's what I was getting at, the settings if updated elsewhere would be overridden and the current user would re-persist their current state. I agree it's a bit of an edge case whereby either way one tab is going to need a refresh and it's not the main thing to consider here.

Really, it's more that I had imagined the decision to always keep the save button enabled would be accompanied by the ability to always actually save the settings (even if they hadn't changed locally). Otherwise, we're providing a clickable button that doesn't actually do anything - personally, I'd find this more confusing as a user as it seems like a bit of an oversight and a bit of a regression from a UI that only enables the button when there's something to save.

It's not a big deal in my view, I'll just be a bit surprised if we take the route of enabling a button that doesn't do anything, that's all :)

**Comment by techanvil** [comment]
Hey @jimmymadon, that's interesting to know. So, I guess there will still be an action associated with the Save button - it's just it won't actually be a "save" action. I guess it works, but it still feels a bit wrong to me. Plus we already have a Cancel button - I don't see a proposal to remove it, but having Save and Cancel buttons next to each other that both do exactly the same thing seems a bit counter-intuitive IMHO...
